services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80

  landing:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./landing:/usr/local/apache2/htdocs

  static-sites:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./static-sites:/usr/local/apache2/htdocs

  calculator:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./calculator:/usr/local/apache2/htdocs

  payment-app:
    build: ./payment-app
    restart: unless-stopped
    environment:
      - PORT=80

  howler:
    build: ./howler
    restart: unless-stopped
    environment:
      - PORT=80

  pet-profile:
    build: ./pet-profile
    restart: unless-stopped
    ports:
      - 3000:3000
